build:
    environment:
        php:
            version: 5.6.9      
#phpunit --coverage-clover=coverage.clover
#wget https://scrutinizer-ci.com/ocular.phar
#php ocular.phar code-coverage:upload --access-token="your-token" --format=php-clover coverage.clover